Module 7 task 2
htmlacademy-nodejs/code-and-magick pull request #17
Opened 2018-10-23 13:26 UTC by kicumkicum

2018-10-23 15:59 UTC, zeckson requested changes
Надо избавиться от `// eslint-disable-next-line` в проекте

2018-10-23 15:59 UTC, zeckson commented on src/wizards/route/error.js
> +  const ERROR_HANDLER = (err, req, res, next) => {
```suggestion
  const ERROR_HANDLER = (err, req, res, _next) => {
```

2018-10-23 15:59 UTC, zeckson commented on src/wizards/route/index.js
> +const wizardsRouter = express.Router();
```suggestion
const wizardsRouter = new express.Router();
```

2018-10-24 10:16 UTC, kicumkicum commented on src/wizards/route/index.js
> +const wizardsRouter = express.Router();
Исправил в коде

2018-10-24 10:17 UTC, kicumkicum commented on src/wizards/route/error.js
> +  const ERROR_HANDLER = (err, req, res, next) => {
Исправил в коде

2018-10-24 10:19 UTC, zeckson approved these changes

2018-10-24 10:19 UTC, merged